Perform correct git diff based on branch type.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,16 +4,22 @@ run: &abort_if_no_change
   name: Abort if no changes
   command: |
     set +x
-    git fetch origin develop:develop
-    git branch
 
-    GIT_DIFF=$(git diff develop modules/$MODULE_NAME)
-    echo "$GIT_DIFF"
-
-    WORD_COUNT=$(git diff develop modules/$MODULE_NAME | wc -l)
-    echo "$WORD_COUNT"
+    if [ $CIRCLE_BRANCH = "master" ] || [ $CIRCLE_BRANCH = "develop" ] ; then
+      WORD_COUNT=$(git diff HEAD@{1} modules/$MODULE_NAME | wc -l)
+    elif [[ $CIRCLE_BRANCH ==  feature/* ]] ; then
+      git fetch origin develop:develop
+      WORD_COUNT=$(git diff develop modules/$MODULE_NAME | wc -l)
+    elif [[ $CIRCLE_BRANCH ==  hotfix/* ]] ; then
+      git fetch origin master:master
+      WORD_COUNT=$(git diff master modules/$MODULE_NAME | wc -l)
+    else
+      echo "Invalid branch name pattern!"
+      exit 1
+    fi
 
     if [ $WORD_COUNT -eq 0 ] ; then
+      echo "No differences for this module. Skipping."
       circleci step halt
     fi
 
